project:
  type: website
  output-dir: docs

website:
  title: "Genuary Submissions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: FAQ.qmd
        text: FAQ

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

